version: "3"
services:
  myflask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: admin
      MONGO_PASS: password
      MONGO_HOST: mongodb     # must match service name below
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - mongo-network

  mongodb:
    image: mongo
    container_name: mongo_new
    ports:
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-expressdb
    depends_on: 
      - mongodb
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
